# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [6]:
a=np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [7]:
a.shape

(40,)

5. Print the type of the previous array in question 3

In [8]:
type(a)

numpy.ndarray

6. Print the numpy version and the configuration


In [11]:
print("numpy version is :: ")
np.__version__
print("configuration is :: ")
np.show_config()

numpy version is :: 
configuration is :: 
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/Anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/Anaconda\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/Anaconda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/Anaconda\\Library\\include']


7. Print the dimension of the array in question 3


In [12]:
print("the dimension is :: ")
a.ndim

the dimension is :: 


1

8. Create a boolean array with all the True values

In [14]:
np.full((5), True, dtype=bool)

array([ True,  True,  True,  True,  True])

9. Create a two dimensional array




In [15]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

10. Create a three dimensional array



In [16]:
np.arange(16).reshape(2,4,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [27]:
b=np.arange(10)
print("Reverse of Array is :: ")
b[::-1]

Reverse of Array is :: 


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

12. Create a null vector of size 10 but the fifth value which is 1 

In [30]:
c=np.zeros(10)
c[5]=1
c

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [31]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [34]:
arr = np.array([1, 2, 3, 4, 5],float)
arr.dtype

dtype('float64')

In [37]:
arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [39]:
arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])
arr3=arr1==arr2
arr3

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [40]:
d=np.arange(10)
d
print("odd numbers ::")
d[d%2==1]

odd numbers ::


array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [44]:
d=np.arange(10)

d[d%2==1]=-1
d

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [46]:
arr = np.arange(10)
arr[[5,6,7,8]]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [50]:
e=np.ones((5,5))
e[1:-1,1:-1]=0
e

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [57]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[1,1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [61]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0]=64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [69]:
a=np.arange(10).reshape(2,5)
a[0]


array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [73]:
a=np.arange(10).reshape(2,5)
a[1,2]

7

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [74]:
a=np.arange(10).reshape(2,5)
a[0:,3]


array([3, 8])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [81]:
r=np.random.randn(10,10)
print(f"THe minimum is :: {r.min()} ")

print(f"THe maximum is :: {r.max()}")



THe minimum is :: -2.267998560004621 
THe maximum is :: 2.175463714769997


In [83]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
a[a==b]

array([2, 2, 4, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [88]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)


(array([1, 3, 5, 7], dtype=int64),)

In [89]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  
data = np.random.randn(7, 4)
data[names!="Will"]






array([[ 1.43101545, -1.08757803,  0.33522201, -0.60929299],
       [ 0.56596391, -0.18977315, -0.26790659, -0.58653286],
       [ 0.34027064,  0.83152001, -0.97826019,  2.02288318],
       [-0.01612377, -0.98459962,  0.50880171,  1.02940194],
       [ 1.2843446 ,  0.13759755, -0.18928075,  1.14036002]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [90]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[(names!="Will") | (names!="Joe")]

array([[ 0.51154748,  0.25287866, -0.06151434,  0.785667  ],
       [-0.72105696, -0.43874291, -1.00825517, -1.44920936],
       [ 2.30175861,  0.60481887,  0.29976429, -1.12472873],
       [-1.53288608, -1.16697413,  0.29294356, -0.04539744],
       [ 1.64993656,  0.39919502, -0.24570799, -0.39675972],
       [ 0.47887267,  2.25660538,  0.29283142, -0.17283142],
       [-0.69231729, -0.5607381 ,  0.76009883,  0.09626047]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [91]:
np.arange(15).reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [92]:
a=np.arange(16).reshape(2,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

33. Swap axes of the array you created in Question 32

In [94]:
a=np.arange(16).reshape(2,2,4)
np.swapaxes(a,0,1)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [99]:
a=np.arange(10)
a[a<0.5]=0
np.sqrt(a)




array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [103]:
a=np.random.randn(12)
b=np.random.randn(12)
c=np.maximum(a,b)
print(f"The maximum values are :: {c}")

The maximum values are :: [ 1.4401075   0.78581463  0.94752702  0.01238686 -0.82847579 -1.28329956
  0.89966131  0.57132163 -0.12021453  0.60112511 -0.03944452  1.32486791]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [105]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [107]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a, b)


array([1, 2, 3, 4])

In [108]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(sampleArray)
x = np.delete(sampleArray, obj = 1, axis=1)
print("deleteing column \n", x)
newColumn = np.array([[10,10,10]])
y = np.insert(x, 1, newColumn,1)
print("New column \n", y)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
deleteing column 
 [[34 73]
 [82 12]
 [53 66]]
New column 
 [[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [110]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [112]:
r=np.random.randn(20)
np.cumsum(r)





array([ 0.65365252, -0.91133096, -1.31808366, -2.46128338, -1.53996753,
       -3.24625462, -1.20764491, -2.47110408, -2.64537486, -2.06216001,
       -0.98438153, -2.7205283 , -3.64283551, -3.08068453, -3.79872672,
       -2.32946117, -2.16354599, -2.97745248, -4.49139904, -3.51275885])