# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
import numpy as np
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [15]:
a=np.arange(10).reshape(2,5)
b=np.ones((2,5),int)
print(f"Array a is \n {a}")
print(f"Array b is \n {b}")
print(f"After stacking Vertically it becomes :: \n {np.vstack((a,b))}")




Array a is 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Array b is 
 [[1 1 1 1 1]
 [1 1 1 1 1]]
After stacking Vertically it becomes :: 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [16]:
a=np.arange(10).reshape(2,5)
b=np.ones((2,5),int)
print(f"Array a is \n {a}")
print(f"Array b is \n {b}")
print(f"After stacking horizantally it becomes :: \n {np.hstack((a,b))}")

Array a is 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Array b is 
 [[1 1 1 1 1]
 [1 1 1 1 1]]
After stacking Vertically it becomes :: 
 [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [30]:
arr=([1,2,3],[4,5,6],[7,8,9])
arr1d=np.array(arr)
print(f"Array of arrays is :: \n{arr1d}")
arr1d.ravel()

Array of arrays is :: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [34]:
a=np.arange(15).reshape(3,5)
print(f"2d arrray is :: \n {a}")
b=a.ravel()
print(f"after converting in 1d :: \n {b}")

2d arrray is :: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
after converting in 1d :: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [35]:
a=np.arange(15)
print(f"1d Array is :: \n {a}")
b=a.reshape(5,3)
print(f"After converting 1d Array into 2d Array  :: \n {b}")


1d Array is :: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
After converting 1d Array into 2d Array  :: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


## Question:7

### Create 5x5 an array and find the square of an array?

In [37]:
s=np.arange(25).reshape(5,5)
print(f"Array is :: \n{s}")
d=np.power(s,2)
print(f"After taking square the Array becomes :: \n{d}")

Array is :: 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
After taking square the Array becomes :: 
[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


## Question:8

### Create 5x6 an array and find the mean?

In [39]:
s=np.arange(30).reshape(5,6)
print(f"Array is :: \n{s}")
d=np.mean(s)
print(f"The mean of the array 's' is :: {d}")

Array is :: 
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
The mean of the array 's' is :: 14.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [46]:
s=np.arange(30).reshape(5,6)
print(f"Array is :: \n{s}")
d=np.mean(s)
print(f"the standard deviation of the previous array is :: {np.std(d)}")


Array is :: 
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
the standard deviation of the previous array is :: 0.0


## Question:10

### Find the median of the previous array in Q8?

In [47]:
p=np.arange(30).reshape(5,6)
print(f"Array is :: \n{p}")
a=np.mean(p)
print(f"the median of the previous array is :: {np.median(a)}")

Array is :: 
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
the median of the previous array is :: 14.5


## Question:11

### Find the transpose of the previous array in Q8?

In [49]:
s=np.arange(30).reshape(5,6)
print(f"Array is :: \n{s}")
w=s.T
print(f"After taking transpose of the array 's' it becomes :: \n {w}")

Array is :: 
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
After taking transpose of the array 's' it becomes :: 
 [[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [55]:
z=np.arange(16).reshape(4,4)
print(f"The array is \n{z}")
print(f"The sum of diagonal elements is {np.trace(z)}")

The array is 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
The sum of diagonal elements is 30


## Question:13

### Find the determinant of the previous array in Q12?

In [56]:
z=np.arange(16).reshape(4,4)
print(f"The array is \n{z}")
print(f"the determinant is :: {np.linalg.det(z)}")

The array is 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
the determinant is :: 0.0


## Question:14

### Find the 5th and 95th percentile of an array?

In [57]:
per=np.arange(10)
print(f"The array is :: \n {per}")
print(f"5th percentile of arr : {np.percentile(per, 5)}")
print(f"95th percentile of arr : {np.percentile(per, 95)}")

The array is :: 
 [0 1 2 3 4 5 6 7 8 9]
5th percentile of arr : 0.45
95th percentile of arr : 8.549999999999999


## Question:15

### How to find if a given array has any null values?

In [60]:
a=np.arange(10)
print(f"the array is {a}")
print("it contains '0' so :: ")
a.all()

the array is [0 1 2 3 4 5 6 7 8 9]
it contains '0' so :: 


False